import QtQuick
import Quickshell
import Quickshell.Io

// Autogenerated, DO NOT EDIT THIS FILE
Item {
	property color focus_muted: "#b295ff"
	property color focus_color: "#924fdc"
	property color focus_off: "#3e2d6d"
	property color offset_color: "#5effdf"
	property color offset_muted: "#4593a5"
    property color bg: "#0a0e2e"
	property color fg: "#fffdeb"
}