#!/bin/bash

CACHE="$1"
OUTPUT="$HOME/.config/hypr/sources/_colors.conf"

source "$CACHE"

# Hex to rgba()
hex_rgba() {
	local hex="${1#"#"}"
	echo "rgba(${hex}ff)"
}

cat > "$OUTPUT" <<EOF
# Hyrpland colors
# Autogenerated, DO NOT EDIT THIS FILE

\$bg = $(hex_rgba "$bg")
\$fg = $(hex_rgba "$fg")

\$black = $(hex_rgba "$black")
\$red = $(hex_rgba "$red")
\$green = $(hex_rgba "$green")
\$yellow = $(hex_rgba "$yellow")
\$blue = $(hex_rgba "$blue")
\$magenta = $(hex_rgba "$magenta")
\$cyan = $(hex_rgba "$cyan")
\$white = $(hex_rgba "$white")
\$black_alt = $(hex_rgba "$black_alt")
\$red_alt = $(hex_rgba "$red_alt")
\$green_alt_alt = $(hex_rgba "$green_alt")
\$yellow_alt = $(hex_rgba "$yellow_alt")
\$blue_alt = $(hex_rgba "$blue_alt")
\$magenta_alt = $(hex_rgba "$magenta_alt")
\$cyan_alt = $(hex_rgba "$cyan_alt")
\$white_alt = $(hex_rgba "$white_alt")

\$main = $(hex_rgba "$main")
\$main_alt = $(hex_rgba "$main_alt")
EOF
