#!/bin/bash

CACHE="$1"
OUTPUT="$HOME/.config/kitty/_colors.conf"

source "$CACHE"

cat > "$OUTPUT" <<EOF
# Kitty colors
# Autogenerated, DO NOT EDIT THIS FILE
color0 $black
color1 $red
color2 $green
color3 $yellow
color4 $blue
color5 $magenta
color6 $cyan
color7 $white
color8 $black_alt
color9 $red_alt
color10 $green_alt
color11 $yellow_alt
color12 $blue_alt
color13 $magenta_alt
color14 $cyan_alt
color15 $white_alt

background $bg
foreground $fg

active_tab_background $main
active_tab_foreground $fg
inactive_tab_background $black
inactive_tab_foreground $fg
EOF
