#!/bin/bash

CACHE="$1"
OUTPUT="$HOME/.config/quickshell/Core/Colors.qml"

source "$CACHE"

cat > "$OUTPUT" <<EOF
import QtQuick
import Quickshell
import Quickshell.Io

// Autogenerated, DO NOT EDIT THIS FILE
Item {
	property color mainColor: "$main"
	property color mainAltColor: "$main_alt"
	property color bgColor: "$bg"
	property color fgColor: "$fg"
	property color blackColor: "$black"
	property color blackAltColor: "$black_alt"
	property color whiteColor: "$white"
	property color whiteAltColor: "$white_alt"
}
EOF
