#
# Kitty config file
#

include ~/.config/theme/output/kitty_colors.conf

#
# VISUAL
#

background_opacity 0.8

#
# FONT
#

font_family MononokiNerdFont

#
# CURSOR
#

#cursor_text_color #fffdeb
cursor_shape block
cursor_shape_unfocused unchanged
cursor_blink_interval 0.5 ease-in-out
cursor_trail 1

#
# KEYBINDS
#

# Copy & Paste
# REMAKE THIS KEYBIND
# map cmd+c copy_or_noop
# map cmd+v paste_from_clipboard

# Scrolling
map shift+up scroll_line_up
map shift+down scroll_line_down
map ctrl+up scroll_page_up
map ctrl+down scroll_page_down

# Tabs
map ctrl+t new_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+w close_tab
map ctrl+n set_tab_title
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4

#
# TABS VISUALS
#

tab_bar_edge top
tab_bar_margin_width 0
tab_bar_margin_height 0 5
tab_bar_align left
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
