#!/bin/bash

CACHE="$1"
DEST="$HOME/.config/starship.toml"
OUTPUT=$(readlink -f "$DEST")
temp=$(mktemp)

source "$CACHE"

# Delete block
awk '
	BEGIN { skip=0 }
	/# START AUTOGENERATED THEME/ { skip=1; next }
	/# END AUTOGENERATED THEME/ { skip=0; next }

	skip == 0 { print }
' "$DEST" > "$temp"

# Add block
cat >> "$temp" <<EOF

# START AUTOGENERATED THEME
palette = "theme"

[palettes.theme]
bg = "$bg"
fg = "$fg"
black = "$black"
red = "$red"
green = "$green"
yellow = "$yellow"
blue = "$blue"
magenta = "$magenta"
cyan = "$cyan"
white = "$white"
black_alt = "$black_alt"
red_alt = "$red_alt"
green_alt = "$green_alt"
yellow_alt = "$yellow_alt"
blue_alt = "$blue_alt"
magenta_alt = "$magenta_alt"
cyan_alt = "$cyan_alt"
white_alt = "$white_alt"
main = "$main"
main_alt = "$main_alt"
# END AUTOGENERATED THEME
EOF


mv "$temp" "$OUTPUT"
