$bg = rgba(0a0e2eff)
$fg = rgba(fffdebff)
$black = rgba(0a0e2fff)
$red = rgba(d53c6aff)
$green = rgba(22c278ff)
$yellow = rgba(ffc587ff)
$blue = rgba(3f7de0ff)
$magenta = rgba(924fdcff)
$cyan = rgba(4593a5ff)
$white = rgba(fffdebff)
$black_alt = rgba(0a0e2fff)
$red_alt = rgba(fd75caff)
$green_alt = rgba(60ff65ff)
$yellow_alt = rgba(fffcc8ff)
$blue_alt = rgba(5fc5ffff)
$magenta_alt = rgba(b295ffff)
$cyan_alt = rgba(5efdf7ff)
$white_alt = rgba(fffdebff)
$main = rgba(924fdcff)
$main_alt = rgba(b295ffff)

