#
# AUTOSTART
#

# SSH agent and key, for GitHub
exec-once = eval ssh-agent $SHELL
exec-once = ssh-add .ssh/id_ed25519

# Start hyprland plugins
exec-once = hyprpm reload

# Start hyprpaper and AGS scripts
exec-once = hyprpaper
