-- Hyrpland colors
-- Autogenerated, DO NOT EDIT THIS FILE

bg = "rgba(0a0e2eff)"
fg = "rgba(fffdebff)"

focus_muted = "rgba(b295ffff)"
focus = "rgba(924fdcff)"
focus_off = "rgba(3e2d6dff)"

special = "rgba(5effdfff)"
special_muted = "rgba(4593a5ff)"

red = "rgba(d53c6aff)"
green = "rgba(22c278ff)"
yellow = "rgba(ffc587ff)"
blue = "rgba(3f7de0ff)"
magenta = "rgba(924fdcff)"
cyan = "rgba(4593a5ff)"
red_alt = "rgba(fd75caff)"
green_alt_alt = "rgba(60ff65ff)"
yellow_alt = "rgba(fffcc8ff)"
blue_alt = "rgba(5fc5ffff)"
magenta_alt = "rgba(b295ffff)"
cyan_alt = "rgba(5efdf7ff)"

main = "rgba(924fdcff)"
main_alt = "rgba(b295ffff)"
