import QtQuick
import Quickshell
import Quickshell.Io

// Autogenerated, DO NOT EDIT THIS FILE
Item {
	property color mainColor: "#924fdc"
	property color mainAltColor: "#b295ff"
	property color bgColor: "#0a0e2e"
	property color fgColor: "#fffdeb"
	property color blackColor: "#0a0e2f"
	property color blackAltColor: "#0a0e2f"
	property color whiteColor: "#fffdeb"
	property color whiteAltColor: "#fffdeb"
}
