# HYPRLAND CONFIGURATION FOR TOKYONEON

#
# SOURCES
#

source = ~/.config/hypr/sources/variables.conf
source = ~/.config/hypr/sources/autostart.conf
source = ~/.config/hypr/sources/decorations.conf
source = ~/.config/hypr/sources/animations.conf
source = ~/.config/hypr/sources/keybinds.conf

#
# MONITORS
#

# Main PC
monitor = DP-1, 1920x1080@144, 0x0, 1
monitor = DVI-D-1, 1920x1080@60, 1920x0, 1

# Laptop
# monitor = auto, auto, 0x0, 1

#
# WINDOWRULES (DEFAULTS)
#

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#
# WORKSPACERULES
#

# Custom rule for Desktop PC, change for other screens or comment for laptops
workspace = 1, monitor:DP-1

#
# LAYOUTS
#

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0# Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1 

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

