color0 #0a0e2f
color1 #d53c6a
color2 #22c278
color3 #ffc587
color4 #3f7de0
color5 #924fdc
color6 #4593a5
color7 #fffdeb
color8 #0a0e2f
color9 #fd75ca
color10 #60ff65
color11 #fffcc8
color12 #5fc5ff
color13 #b295ff
color14 #5efdf7
color15 #fffdeb

background #0a0e2e
foreground #fffdeb

active_tab_background #924fdc
active_tab_foreground #fffdeb
inactive_tab_background #0a0e2f
inactive_tab_foreground #fffdeb
