# VARIABLES

#
# COLORS
#

$colorbg = rgb(0e0a2f)
$colormain = rgb(924fdc)
$colormainlight = rgb(b295ff)
$colorfg = rgb(fffdeb)

#
# DEFAULT PROGRAMS
#

$terminal = kitty
$fileManager = kitty -e ranger
$menu = rofi -show run
$browser = opera
